### PR TITLE
GemStats.org

### PR DESCRIPTION
**Pull request by bcardarella**
Added GemStats.org

### CODE REVIEW

**Comment by luislavena** [comment]
Hello!

Do you guys already published something of the data gathered? It will be good to show what you guys do and not just point people to a form for they to upload something.

I mean, having gathered 889 Gemfiles, can you start showing some pretty stats about them?

**Comment by bcardarella** [comment]
Loren Segal published the data:

http://gnuu.org/2011/10/19/gem-downloads-and-usage/
http://gnuu.org/2011/10/21/plausible-explanations-for-crazy-gem-download-counts/
- Brian

On Thu, Dec 15, 2011 at 9:19 AM, Luis Lavena
reply@reply.github.com
wrote:

**Comment by luislavena** [comment]
@qrush do you approve the inclusion of gemstats?

**Comment by qrush** [comment]
Where's the github code for it? This site is meant for OSS contributions.

**Comment by bcardarella** [comment]
Not worth the time

**Comment by qrush** [comment]
Just catching up on this, any reason why you feel this way, @bcardarella? Sounds like someone else who may want to build a similar gemfile-parsing service may find it useful to browse.

**Comment by bcardarella** [comment]
I released the Gemfile parser a while ago as a gist: https://gist.github.com/04020677ec4f8186d869

tbh, that's really the only interesting part of the app

**Pull request closed without merging**
